# Generated by Django 3.0.3 on 2020-05-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='IntNet',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
