# Generated by Django 3.0.3 on 2020-05-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_net_intnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinterface',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
